### ISSUE TITLE
Make BoilR "forget" created shortcuts

### ISSUE THREAD

**Issue by bkoehle2** [PhilipK/BoilR#131]
(As suggested making a new issue :)

I know in this instance there was a problem with how BoilR was creating the shortcut, but you had said previously that BoilR will remember what games it makes shortcuts for. Do you think there is a use case for clearing some of that information?

I suppose ideally BoilR makes the shortcuts correctly, but there may be instances where small adjustments to the launch options are necessary to get games to run. And if BoilR wipes that information every time an import is done, maybe there is a case for allowing the use to have BoilR "forget" it added a game so that adjustments can be made to the shortcut without it being overwritten (but still allowing BoilR to import the game art at first)?

Personally I do not have a use case for this now, and I can't say for certain there would be one in the future, but could be something to put on the back burners. Appreciate your work on this tool Philip!

**Comment by rmaia** [comment]
I often have to use [HeroicBashLauncher](https://github.com/redromnon/HeroicBashLauncher) to get a working launch command (especially for GOG games) and I have to manually change the shortcut used by the app. These changes get overwritten by BoilR when I re-run it to add a new game. So that could be an example use case. I also manually changed the icon for Prey (2017) because it found the icon for Prey (2006) instead, and that gets overwritten with every BoilR run too, but that's a much smaller issue :) 

I can't thank you enough for BoilR @PhilipK , it's literally the tool making other launchers usable on Steam Deck for me now. It's a godsend. Really appreciate it, let me know if there's any way to help!

**Comment by PhilipK** [comment]
This is in version https://github.com/PhilipK/BoilR/releases/tag/v.1.3.12
