### ISSUE TITLE
BoilR on Steam Deck Result::unwrap() Err Utf8Error

### ISSUE THREAD

**Issue by Sarume** [PhilipK/BoilR#20]
(First issue i ever reported so sorry if it's gonna be a bit chaotic)

Version used: v0.9.0
Tested on: Steam Deck - SteamOS3

Upon running the "linux_BoilR" binary in Konsole, after allowing it to be executable, i got the following output:

Found 1 user(s)
Found 25 shortcuts for user: /home/deck/.steam/steam/userdata/--------- (edited out my user number)
thread 'main' panicked at 'called Result::unwrap() on an Err value: Utf8Error { valid_up_to: 33, error_len: Some(1) }', src/itch/butler_db_parser.rs:33:55
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

I do get the same output when running "linux_ui_BoilR" too. The settings were set up like i did on my Arch install where it worked seemingly as supposed to be.

Googling the error message didn't get me far as I'm neither versed in rust and installing packages manually on steamOS is advised against due to the nature of updates having the possibilty to undo packages that may be installed manually via pacman on SteamOS.

**Comment by PhilipK** [comment]
Hi, awesome that you are testing on the Steam Deck!

Do you actually have itch installed? Which platforms are you trying synchronize for?

**Comment by PhilipK** [comment]
It looks like this is a result of the error handling here:
https://github.com/PhilipK/BoilR/blob/main/src/itch/butler_db_parser.rs#L33

I will have a look at it later.

**Comment by Sarume** [comment]
Someone linked me your project and it seemed to me like a really useful idea for the deck especially since setting up custom links is quite a bit of a hassle, especially if you don't have a USB-C hub to connect a keyboard to the deck and since you said you were planning for deck support and i have my hands on one, why not try to help out? 

But yes, i've only been trying to grab from itch so far and yes i've been using it manually before and linking games manually. 
I think i have heroic/legendary set up, but didn't try to pull from them yet.

**Comment by PhilipK** [comment]
BoilR parses the Itch "database" file, and it seems that there is an error parsing it right now. Fortunately I didn't handle an error like that "properly" so the program just crashes instead of just finishing the other. First, I will try to fix that it crashes and instead just report an error.

After that I will try to look at why the error is there in the first place, and try to fix that. For now, you can continue using BoilR for the other platforms by disabling the Itch integration for now.

**Comment by Sarume** [comment]
What confuses me about it is that it works fine on my Arch install, which makes me wonder if it may be due to some missing package/function it is expecting that's not installed on the deck by default

**Comment by PhilipK** [comment]
I don't actually think it is steam deck specific, i think it is itch version specific. I also run Arch myself, and it works fine there (at least last time I checked). I can tell you it is not because of any missing packages or functions since BoilR is standalone and does not rely on any packages. 

From the error it looks like it is the itch database file has some content that is not is not utf8 (format for text) and BoilR expects it to be.

**Comment by PhilipK** [comment]
I have made a new release:
https://github.com/PhilipK/BoilR/releases/tag/v.0.9.1

Try and see if that helps, if nothing else it should prevent it from crashing.

**Comment by Sarume** [comment]
Found 2 user(s)
Found 0 shortcuts for user: /home/deck/.steam/steam/userdata/0
Found 0 game(s) for platform Itch
Setting for platform Lutris are invalid, reason: No such file or directory (os error 2)
Saved 0 shortcuts
Finished synchronizing games in: 4.684277ms
Found 26 shortcuts for user: /home/deck/.steam/steam/userdata/--------
Found 0 game(s) for platform Itch
Setting for platform Lutris are invalid, reason: No such file or directory (os error 2)
Saved 26 shortcuts
Finished synchronizing games in: 3.191662ms
Checking for game images
Searching for TheDarkMod
Searching for Shattered Pixel Dungeon
Searching for Zera Myths Awaken
Searching for FreeTube
Searching for Underhero
Searching for Game Jolt Client
Searching for Ponyvania
Searching for Blastem
Searching for Viscerafest.x86_64
Searching for Viscerafest.exe
Searching for Minetest
Searching for Code Bunny
Searching for TonightWeRiot
No images needed

-----

This is with the new version - no idea where that first user entry is coming from, it's happening with the old version too now for some reason. 
It seems to be detecting itch, but not the games i've installed in the meantime to test whether they're picked up. The entries it's searching art for are custom links i added manually earlier.

**Comment by PhilipK** [comment]
Thank you for your prompt feedback.

It is going to be hard to figure out what is wrong, since I don't have access to a steam deck or your itch.io database file.

But, there is a workaround.

https://lutris.net/games/itchio/

If you install lutris and add itch.io from there, then BoilR should be able to launch the games through lutris.


If you really want it to work without lutris you can try to email me your itch.io database file.

**Comment by Sarume** [comment]
i'll try running it through lutris and see if that works.

If it helps you i can still gladly send you the database file

**Comment by Sarume** [comment]
Hmpf. Guess flatpak lutris is still buggy on the deck. at least it won't let me install itch that way, i'm gonna send you my db file

**Comment by PhilipK** [comment]
@Sarume I tried to use your butlerdb file on my laptop, and interestingly enough it finds one game in there.
Can you confirm that there is only one game in there?

**Comment by PhilipK** [comment]
Nevermind my previous comment, I think i found the problem. 
It should be fixed in this commit:
https://github.com/PhilipK/BoilR/commit/dbe7abdcbc4dbc9c95700f92c96d3024fb23dbc0

New release incoming.

**Comment by PhilipK** [comment]
@Sarume can you try this new release ? https://github.com/PhilipK/BoilR/releases/tag/v.0.9.2

**Comment by Sarume** [comment]
seems to be working now.
Detects the 8 games i have installed and adds them to steam. (one of them has been identified wrongly for some reason though)

**Comment by PhilipK** [comment]
Awesome, I am going to close this issue, can you create a new one about the wrongly identified game?
