### ISSUE TITLE
Support for Steam on Distrobox

### ISSUE THREAD

**Issue by Heus-Sueh** [PhilipK/BoilR#374]
**Is your feature request related to a problem? Please describe.**
If steam is in a container, BoilR will pass the shortcuts of all programs with the wrong command

## Wrong:
`run --command=bottles-cli com.usebottles.bottles run -b "Gaming" -p "DARK SOULS III"`
![image](https://github.com/PhilipK/BoilR/assets/98482469/62bb8ded-2fc2-4c4a-a633-412e31452f59)

## Right:
`distrobox-host-exec flatpak run --command=bottles-cli com.usebottles.bottles run -b "Gaming" -p "DARK SOULS III"`
![image](https://github.com/PhilipK/BoilR/assets/98482469/c0ffdb07-2171-48ae-b9bb-b59894fb26a9)

`distrobox-host-exec` allows the container to invoke the host's flatpak

**Describe the solution you'd like**
"distrobox-host-exec" before all commands that interact with the host's flatpak

**Comment by s-20** [comment]
This isn't quite right; Steam needs a "Target" in order to show an icon for the game/app. Instead of moving everything to Launch Options, you should append `distrobox-host-exec` to the initial `flatpak` in the Target entry. A la:

![Screenshot from 2024-02-19 12-20-14](https://github.com/PhilipK/BoilR/assets/52514259/615d3639-e82f-46a5-a486-f38cb9a9b011)

(sorry for the Adwaita theming...)

This way, Steam can still apply an icon to the game/app (notice that it vanishes in OP's example pictures...)

I don't know how tricky autodetection would be, but a radio switch in the options menu (something like "is Steam running from a Distrobox Container?") would do wonders, because I feel like anyone running Steam from Distrobox at the very least *knows* they're doing that.
