### ISSUE TITLE
Erroneous error with collections

### ISSUE THREAD

**Issue by Untz64** [PhilipK/BoilR#88]
I regularly get the following error during import:
```
Writing 4 collections
Could not write collections, make sure steam is shut down
```

Steam *is* shut down when importing, and the collections are created/written to successfully.

**Comment by PhilipK** [comment]
You are unfortunately not the only one that experiences this.
https://github.com/PhilipK/BoilR/issues/71

BoilR uses a library to write to steams "collections database file", and some times it fail. Normally it is because steam has a lock on the file (because it is open) but it can be other things, but I can't really get enough information to figure out what, so I just made BoilR write that, because in most cases that is the reason.

I will have to take another look at the feature (when I get time).

**Comment by Untz64** [comment]
Thanks! Like I said, I don't think in my case that it's actually erroring out; the result is correct, I just felt like in my case it was a false positive on the error checking. My apologies if this is a duplicate issue though.

**Comment by PhilipK** [comment]
Closing this because it is a so close to #71
